### PR TITLE
Swiftify

### PR DESCRIPTION
**Pull request by FrancisBehnen**
Removes the need to cast types back and forth almost entirely.

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
The comments do clutter the code a bit so we may want to remove these before merging.

**Comment by 3lvis** [comment]
What's left here?

**Comment by FrancisBehnen** [comment]
If you don't want comments in master then yes, just removing comments. Otherwise we can merge now.

**Comment by 3lvis** [comment]
I'll review and remove the comments in a separate PR. Looks like the tests are running fine, too.

Great work!

**Pull request merged**
