### PR TITLE
Add support for filtering NSNull

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by 3lvis** [comment]
screen shot 2016-08-26 at 13 25 22

**Comment by FrancisBehnen** [comment]
Does `nil` comply with `NSNull()` if it is converted to `NSObject()`? If not this commit removes filtering of completely `nil` objects as far as I can see.

**Comment by 3lvis** [comment]
How can you have a completely `nil` object?

Could you provide an example, please? If you see the unit test it fixes filtering `null` objects found in JSON, that's what we had before.

**Comment by FrancisBehnen** [comment]
Depends on the `map{}` function. `remotePrimaryKeys` is of type `[AnyObject?]` so purely based on the types it's possible. I'll look into it further when I have more time.

**Comment by 3lvis** [comment]
Thanks a lot <3

**Comment by FrancisBehnen** [comment]
No heart anymore 💔</3 :( ?

**Comment by 3lvis** [comment]
Hahahaha ❤️❤️❤️❤️❤️

**Comment by FrancisBehnen** [comment]
See #35

**Pull request merged**
